### ISSUE TITLE
能否使用低版本的.net版本

### ISSUE THREAD

**Issue by Hellobaka** [Scighost/PixivApi#1]
.net6有点太高了，如果使用.netstandard2.0之类的基层版本框架更适合做nuget包吧

**Comment by Scighost** [comment]
自己改一改很容易

``` xml
<PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>10</LangVersion>
</PropertyGroup>
<ItemGroup>
    <PackageReference Include="System.Net.Http.Json" Version="7.0.0" />
    <PackageReference Include="System.Text.Json" Version="7.0.0" />
</ItemGroup>
```

然后把这三个不兼容的错误修复完就行

<img width="680" alt="image" src="https://user-images.githubusercontent.com/61003590/204176411-18b3e3c3-31a8-4aad-a7ce-0859cd98e704.png">

**Comment by Hellobaka** [comment]
嗯，自己拉代码下来改肯定是可以，如果nuget这边也一起改了大概会更方便一些吧。总之还是谢谢啦
